### ISSUE TITLE
Spacing issue in comparison chart 

### ISSUE THREAD

**Issue by f2e6** [zen-browser/www#111]
![image](https://github.com/user-attachments/assets/12631ee2-6b13-4ff1-98c7-8e6f302e8eff)

Issue shows up on Zen and regular firefox.

**Comment by ktz-dev** [comment]
Hi @swarnendu19 

In your screenshot the headings are out of alignment with the checkboxes below them and also the table styling is not responsive. If the table width expands or shrinks then the elements inside will be off-center. 

I was trying to help someone through fixing this properly but I haven't heard back (see #63). I have shared my feedback with you on your PR #111. Take a look and let me know what you think.

Thanks

**Comment by ktz-dev** [comment]
#63 has committed their changes. It is fixed in their PR. 

<img width="681" alt="Screenshot 2024-08-29 at 9 05 44 AM" src="https://github.com/user-attachments/assets/3bc2fc92-c870-4229-a54f-1531fa2be7c8">
<img width="481" alt="Screenshot 2024-08-29 at 9 06 11 AM" src="https://github.com/user-attachments/assets/61f37d2e-c656-4e83-b9e5-936acb871a61">

**Comment by ktz-dev** [comment]
They updated the features page. This table isn't there anymore.

**Comment by swarnendu19** [comment]
Yeah, this #63 is a nice one.
