### ISSUE TITLE
Page content getting bloacked by nav bar

### ISSUE THREAD

**Issue by Tadiwr** [zen-browser/www#163]
![image](https://github.com/user-attachments/assets/57d05d10-0755-4043-95fd-78d3001e0779)

Im just assuming most likely the navbar is supposed to be fixed so that means probably each page should have a margin top the size of the top nav bar to allow for that???

**Comment by NOCanoa** [comment]
do u have any zoom on?
looks normal to me

**Comment by ktz-dev** [comment]
Hi, this is a side-effect of using `position: fixed`. When the position is fixed it means that the element hovers over the page content fixed to a position on the viewport rather than actually being part of the page content itself. Because it is hovering over the page content, it doesn't affect the layout of the other elements beneath it so they can just go behind the fixed element. 

This is just how fixed positioning works. The only fix is to shove some padding or margin to the top of the page beneath it to make it look like the navbar is taking up space.

**Comment by ktz-dev** [comment]
Hi. Yes you aren't correct. It is a side-effect of using `position: fixed`. Fixed elements hover over the page content and don't affect the elements beneath them. 

Using margin-top would work but will lead to the page contents being off center on the Y axis because the div they are contained in is now pushed down by however many pixels by the margin. 

It is best to use `box-sizing: border box` and `padding: 5rem 0` so that the padding is added to both the top and bottom of the inside of the div container. This means the content stays vertically centered. 

In TailwindCSS that's `box-border py-20`.

Note: [Preflight](https://tailwindcss.com/docs/preflight) sets everything to `box-border` by default anyway so you just need to add `py-20` or however much padding to the download.tsx

**Comment by ktz-dev** [comment]
Sorry I'm not doing a very good job explaining. This is what I mean. With padding the text doesn't move. 

![Desktop - 1(1)](https://github.com/user-attachments/assets/670ed423-310f-4903-a2a1-2394ca3ce94d)

**Comment by NOCanoa** [comment]
@ktz-dev verry good explanation but i dont know next/tailwind xD

**Comment by ktz-dev** [comment]
Oh come on. You don't "learn" TailwindCSS. TailwindCSS is not really a CSS library, its more like a style guide on how to write good CSS.

So, instead of what you would typically do:
``` html
<p>Hello World</p>
```
```css
p {
    font-size: 18px;
    font-weight: bold;
    font-style: italic;
}
```

You instead put every css property into its own class, so something like this:

``` css
.text-lg {
    font-size: 18px
}

.font-bold {
    font-weight: bold;
}

.italic {
    font-style: italic;
}
```
this way you can reuse these classes with the CSS you need on every html tag
``` html
<p class="text-lg font-bold italic">Hello World</p>
```

This is so you can see the HTML and the CSS in the same place instead of styles being in a separate file. 

Obviously putting every CSS property into its own class will be a huge CSS file so instead of writing it yourself you just use one that is already written (TailwindCSS). 

You just need to search up the CSS property you would've used on https://tailwindcss.com/ to get the class that property is in.

**Comment by sumukhj1219** [comment]
i can fix this

**Comment by Tadiwr** [comment]
I actually never revisited this commit because I never thought you guys would actually open the issue yourself. Thank you!
