### ISSUE TITLE
The Emoji on the main page looks bad when highlighted

### ISSUE THREAD

**Issue by neurokitti** [zen-browser/www#221]
![image](https://github.com/user-attachments/assets/d03cdec7-aeb4-4be1-b444-becc7015fdf3)

when highlighting it the emoji becomes obvious and looks kinda bad.

**Comment by flyri0** [comment]
This is the expected behavior. The emoji is affected by [background-clip](https://developer.mozilla.org/en-US/docs/Web/CSS/background-clip), but since it has its own colors, those colors are influenced by the background animation. I don’t think this is a real issue.

A possible 'solution' would be to replace the emoji with an SVG and apply the same color as the text to it.

**Comment by NOCanoa** [comment]
any one got a bether slogan? the rocked doesnt look good in my opinion xO

**Comment by ZhenyaGoroh** [comment]
This rocket looks a little bit weird with this fill color. It have to be with its default color or be deleted 🤔.
Maybe create thread in discord so users can suggest the slogan and then create poll with top 3?

**Comment by NOCanoa** [comment]
cheff wants to do somting like this https://discord.com/channels/1088172780480114748/1275868858288177314/1293314880971079874

**Comment by NOCanoa** [comment]
rocket got removed
