### ISSUE TITLE
Unable to open mods from zen mods page using vimium extension

### ISSUE THREAD

**Issue by nanoraptor** [zen-browser/www#257]
On pressing f or F using [vimium](https://addons.mozilla.org/en-US/firefox/addon/vimium-ff/) extension, It will list all the clickable elements in the webpage. But it is not showing the individual mod's page in the site. Ideally it should be near the preview image of the mod. But it is not there, perhaps the html is not encoded properly. Making a part of the image explicitly clickable in HTML will avoid this problem ig. 

![image](https://github.com/user-attachments/assets/32b9ec27-6786-4f5d-99cb-b5ea35252715)

Another issue that bothers me with the site is that if I click "Go Back" from the mod page it goes back to the first mod in the list of the first page irrespective of which mod was in selection previously. If I wanted to go back and click an extension which was previously below the extension I just viewed, I have to go down all the way to get back to where I was previously. This is pretty annoying!!!!!!

![image](https://github.com/user-attachments/assets/708cf252-628e-432e-9906-1cec0928ec5c)

**Comment by Mailootje** [comment]
> On pressing f or F using [vimium](https://addons.mozilla.org/en-US/firefox/addon/vimium-ff/) extension, It will list all the clickable elements in the webpage. But it is not showing the individual mod's page in the site. Ideally it should be near the preview image of the mod. But it is not there, perhaps the html is not encoded properly. Making a part of the image explicitly clickable in HTML will avoid this problem ig.

As far as i can see this is because if we enable this. (normally when you hover over this "card" it will show you a hand click pointer). This is removed (not 100% sure) because if this is on. It will not let you install any mods...


> Another issue that bothers me with the site is that if I click "Go Back" from the mod page it goes back to the first mod in the list of the first page irrespective of which mod was in selection previously. If I wanted to go back and click an extension which was previously below the extension I just viewed, I have to go down all the way to get back to where I was previously. This is pretty annoying!!!!!!

I can look into this tonight and try to fix this.
I will keep you uptodate here

**Comment by taroj1205** [comment]
Hey @nanoraptor, I have fixed the go back link with #270.

For the vimium extension not detecting the card, I have thought of an idea which could potentially fix this.
We can add `role="button"`, and `tabIndex={0}`, to the card (or changing it to a button component), although I am unsure if Zen can still let us install mods with this solution.

Another alternative solution would be for Zen browser to implement API (e.g. `window.zen`) instead of injection on the website.

**Comment by TheRealMG** [comment]
Unfortunately the link for the card is not possible at the moment due to how the browser handles site injection, but we've been actively looking for solutions that don't break. 

As suggested, the `window.zen` API implementation would likely fix the issue and is being looked into.

**Comment by NOCanoa** [comment]
well that mods page no more lul
