### ISSUE TITLE
Zen Twilight link for macOS x86_64 is broken

### ISSUE THREAD

**Issue by thebiblelover7** [zen-browser/www#305]
Previously, https://github.com/zen-browser/desktop/releases/download/twilight/zen.macos-x64.dmg was the right link to download. When trying to download Zen Twilight from https://zen-browser.app/download?twilight now, it results in a 404 from GitHub because of the wrong link.

Now, after commit https://github.com/zen-browser/desktop/commit/444c9138e0de97d61dfc65ab112ce763ee5a0241, the correct link should be https://github.com/zen-browser/desktop/releases/download/twilight/zen.macos-x86_64.dmg

**Comment by thebiblelover7** [comment]
I am still having the issue. Clicking on Download Twilight > macOS > Intel, results in a 404.

**Comment by fal3n-4ngel** [comment]
The issue arises because the release build and twilight build use different names for the macOS Intel build, but the code assumes the same name for both. To resolve this, we can either update the code to handle both names or standardize the build names.
the second option would be better , so ig waiting for them to update it would be better than dropping a useless pullreq
